name: Discord Webhook Notifications

on:
  push:
    branches: [ main ]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "Push to ${{ github.ref_name }}"
          description: |
            **Commit:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.event.head_commit.author.name }}
            [View Commit](${{ github.event.head_commit.url }})
          color: 0x5865F2
          username: GitHub Bot
